title: "Power, Pluralism, & Parity: Intersectional Data Feminism"
description: "Course page from Bryn Mawr College's Intersectional Data Feminism course"
#theme: jekyll-theme-minimal  # or another supported theme like jekyll-theme-cayman
theme: jekyll-theme-cayman
show_sidebar: true  # Some themes support this
