title: "Intersectional Data Feminism Spring 2025"
description: "Course page from Bryn Mawr College's Intersectional Data Feminism course in Spring 2025"
theme: minima  # or another supported theme like jekyll-theme-cayman
