title: "Intersectional Data Feminism Spring 2025"
description: "Course page from Bryn Mawr College's Intersectional Data Feminism course in Spring 2025"
theme: jekyll-theme-minimal  # or another supported theme like jekyll-theme-cayman
