title: "Power, Pluralism, & Parity: Intersectional Data Feminism"
description: "Course page from Bryn Mawr College's Intersectional Data Feminism course"
theme: minima
minima:
  skin: solarized-light


  